### ISSUE TITLE
Cannot build Java wrapper

### ISSUE THREAD

**Issue by QubitPi** [yahoo/mdbm#82]
I've installed MDBM using `make install`, but `mvn verify -DnativeDir=../lib/object/ -DlibDir=object/` gives me the following error. I'm running this command with the config change specified in https://github.com/yahoo/mdbm/pull/81.

I guess `-Djava.library.path=../lib/object/:object/` has some problem.

```
Configuring TestNG with: TestNG652Configurator
Cannot load mdbm_java native library, -Djava.library.path=../lib/object/:object/
start testDontCloseFromPool
finally testDontCloseFromPool
start testInvalidSize
start testInvalidSize
start testPool
opening /home/qubuntu/Documents/mdbm/src/java/test/resources/testv3.mdbm
Tests run: 49, Failures: 4, Errors: 0, Skipped: 19, Time elapsed: 0.379 sec <<< FAILURE! - in TestSuite
initEmptyMdbm(com.yahoo.db.mdbm.TestV4)  Time elapsed: 0.014 sec  <<< FAILURE!
java.lang.UnsatisfiedLinkError: no mdbm_java in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.yahoo.db.mdbm.internal.NativeMdbmAccess.<clinit>(NativeMdbmAccess.java:15)
	at com.yahoo.db.mdbm.internal.NativeMdbmImplementation.mdbm_open(NativeMdbmImplementation.java:444)
	at com.yahoo.db.mdbm.MdbmProvider.open(MdbmProvider.java:140)
	at com.yahoo.db.mdbm.TestSimpleMdbm.initEmptyMdbm(TestSimpleMdbm.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:204)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:107)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:112)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

testDontCloseFromPool(com.yahoo.db.mdbm.internal.TestMdbmPool)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.NoClassDefFoundError: Could not initialize class com.yahoo.db.mdbm.internal.NativeMdbmAccess
	at com.yahoo.db.mdbm.internal.NativeMdbmImplementation.mdbm_open(NativeMdbmImplementation.java:444)
	at com.yahoo.db.mdbm.MdbmProvider.open(MdbmProvider.java:140)
	at com.yahoo.db.mdbm.MdbmProvider.openPool(MdbmProvider.java:83)
	at com.yahoo.db.mdbm.internal.TestMdbmPool.testDontCloseFromPool(TestMdbmPool.java:93)

testPool(com.yahoo.db.mdbm.internal.TestMdbmPool)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.NoClassDefFoundError: Could not initialize class com.yahoo.db.mdbm.internal.NativeMdbmAccess
	at com.yahoo.db.mdbm.internal.NativeMdbmImplementation.mdbm_open(NativeMdbmImplementation.java:444)
	at com.yahoo.db.mdbm.MdbmProvider.open(MdbmProvider.java:140)
	at com.yahoo.db.mdbm.MdbmProvider.openPool(MdbmProvider.java:83)
	at com.yahoo.db.mdbm.internal.TestMdbmPool.testPool(TestMdbmPool.java:45)

testEmptyFirst(com.yahoo.db.mdbm.TestPool)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.NoClassDefFoundError: Could not initialize class com.yahoo.db.mdbm.internal.NativeMdbmAccess
	at com.yahoo.db.mdbm.internal.NativeMdbmImplementation.mdbm_open(NativeMdbmImplementation.java:444)
	at com.yahoo.db.mdbm.MdbmProvider.open(MdbmProvider.java:140)
	at com.yahoo.db.mdbm.MdbmProvider.openPool(MdbmProvider.java:83)
	at com.yahoo.db.mdbm.TestPool.testEmptyFirst(TestPool.java:18)


Results :

Failed tests: 
  TestV4>TestSimpleMdbm.initEmptyMdbm:42 » UnsatisfiedLink no mdbm_java in java....
  TestMdbmPool.testDontCloseFromPool:93 » NoClassDefFound Could not initialize c...
  TestMdbmPool.testPool:45 » NoClassDefFound Could not initialize class com.yaho...
  TestPool.testEmptyFirst:18 » NoClassDefFound Could not initialize class com.ya...

Tests run: 49, Failures: 4, Errors: 0, Skipped: 19

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by QubitPi** [comment]
Solved by running Makefile under `src/java`
